#
# SPDX-FileCopyrightText: 2017-2026 Enedis
#
# SPDX-License-Identifier: Apache-2.0
#
#

kotlin.code.style=official

org.gradle.jvmargs=-Xmx2048M

# IntelliJ Platform Artifacts Repositories
# -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

pluginGroup = fr.enedis.chutney.idea
pluginName = chutney-idea-plugin
chutneyVersion = 5.0.1-SNAPSHOT

# See https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
# for insight into build numbers and IntelliJ Platform versions.
platformVersion = 2025.3.6
pluginSinceBuild = 253

# Opt-out flag for bundling Kotlin standard library.
# See https://plugins.jetbrains.com/docs/intellij/kotlin.html#kotlin-standard-library for details.
kotlin.stdlib.default.dependency = false
